[build-system]
requires = ["hatchling>=1.17.1"]
build-backend = "hatchling.build"

{% include "build-system/base-pyproject.toml" %}
{% include "build-system/base-dev-deps-pyproject.toml" %}
{% include "build-system/base-urls-pyproject.toml" %}

[tool.hatch.version]
{# keep this line here #}
{%- if cookiecutter.project_layout == 'flat' -%}
path = "{{ cookiecutter.package_slug }}/__init__.py"
{% elif cookiecutter.project_layout == 'src' -%}
path = "src/{{ cookiecutter.package_slug }}/__init__.py"
{%- endif %}

{% include "build-system/base-dev-deps-config-pyproject.toml" %}
