[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

{% include "build-system/base-pyproject.toml" %}
{% include "build-system/base-dev-deps-pyproject.toml" %}
{% include "build-system/base-urls-pyproject.toml" %}
{% include "build-system/base-dev-deps-config-pyproject.toml" %}
