repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer

  - repo: local
    hooks:
    {%- if cookiecutter.auto_format_tool == 'blue' +%}
    - entry: blue
      id: blue
      name: blue
    {%- elif cookiecutter.auto_format_tool == 'black' +%}
    - entry: black
      id: black
      name: black
    {%- endif +%}
      exclude: |
        (?x)(
          docs
        )
      files: ""
      language: system
      pass_filenames: true
      stages:
        - commit
      types:
        - python
        - file
        - python

    - entry: flake8
      exclude: ^$
      files: ""
      id: flake8
      language: python
      name: flake8
      pass_filenames: true
      stages:
        - commit
      types:
        - python

    - entry: isort
      exclude: "^.*/js/.*$"
      files: ""
      id: isort
      language: python
      name: isort
      pass_filenames: true
      stages:
        - commit
      types:
        - python

    - entry: mypy
      exclude: ^$
      # note: it would be good to extend this to other apps as well
      files: "{{ cookiecutter.package_slug }}/"
      id: mypy
      language: python
      name: mypy
      pass_filenames: true
      stages:
        - commit
      types:
        - python

    {% if cookiecutter.use_bandit in ['yes', 'y'] -%}
    - entry: bandit
      id: bandit
      language: python
      name: bandit
      args: ['-iii', '-ll', .bandit]
      pass_filenames: true
      stages:
        - commit
      types:
        - python
    {%- endif %}

    {% if cookiecutter.use_pydocstyle == 'yes' -%}
    - entry: pydocstyle
      exclude: ^$
      files: "{{ cookiecutter.package_slug }}/"
      id: pydocstyle
      language: python
      name: pydocstyle
      pass_filenames: true
      stages:
        - commit
      types:
        - python
    {%- endif %}

    {% if cookiecutter.use_vulture == 'yes' -%}
    - entry: vulture
      files: "{{ cookiecutter.package_slug }}/"
      id: vulture
      language: python
      name: vulture
      description: Find unused Python code.
      pass_filenames: true
      stages:
        - commit
      types:
        - python
    {%- endif %}
