name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10  

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "1.*"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: {{ cookiecutter.project_slug }}
        use-mamba: true
        miniforge-variant: Mambaforge

      - name: Install deps
        run: poetry install

      - name: Run semantic release command
        run: |
          npx --yes \
          -p semantic-release \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "@google/semantic-release-replace-plugin" \
          semantic-release --ci
