name: scicookie
channels:
  - nodefaults
  - conda-forge
dependencies:
  - bash
  - git
  - python >=3.8.1,<3.12
  - poetry >=1.5
  - nodejs
  - compilers
  - pip
  - pip:
      - makim==1.12.0
      - paginate
