name: {{ cookiecutter.project_slug }}
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python <3.11
{%- if cookiecutter.build_system == "poetry" %}
  - poetry
{%- elif cookiecutter.build_system == "flit" %}
  - flit
{%- elif cookiecutter.build_system == "mesonpy" %}
  - meson-python
{%- elif cookiecutter.build_system == "setuptools" %}
  - setuptools
  - build
{%- elif cookiecutter.build_system == "pdm" %}
  - pdm
{%- elif cookiecutter.build_system == "hatch" %}
  - hatch
{%- elif cookiecutter.build_system == "maturin" %}
  - maturin
  - rust
{%- endif %}
  - nodejs  # used by semantic-release
  - shellcheck
{%- if cookiecutter.documentation_engine == "sphinx" %}
  - pandoc
{%- endif %}
{%- if cookiecutter.use_mypy == "yes" %}
  - mypy
{%- endif %}
