name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "1.1.0"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: pypkg
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: make test

    - name: Run style checks
      run: |
        pre-commit install
        make lint
        # run lint for the project using the template


  smoke-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-smoke-${{ matrix.smoke_file }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        smoke_file:
          - jupyter-books.sh
          - mkdocs.sh
          - sphinx.sh

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "1.1.0"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: pypkg
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Run Smoke Test (mkdocs)
      run: bash ./tests/smoke/${{ matrix.smoke_file }}

    - name: Run style checks
      run: |
        pre-commit install
        make lint
        # run lint for the project using the template
