name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: poetry install
      - name: Run semantic-release dry
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          npx --yes \
          -p semantic-release \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "@google/semantic-release-replace-plugin" \
          semantic-release --dry
      - name: Run semantic-release ci
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          npx --yes \
          -p semantic-release \
          -p "@semantic-release/commit-analyzer" \
          -p "@semantic-release/release-notes-generator" \
          -p "@semantic-release/changelog" \
          -p "@semantic-release/exec" \
          -p "@semantic-release/github" \
          -p "@semantic-release/git" \
          -p "@google/semantic-release-replace-plugin" \
          semantic-release --ci

  publish-docs:
    needs: [release]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "0.23.0"
        environment-file: conda/dev.yaml
        channels: conda-forge,nodefaults
        activate-environment: pypkg
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install deps
      run: poetry install

    - name: Build the book
      run: make docs

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
